# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 334b62b4e4e86730ee9e31b9be0f107e4f28197e1374e49ed7be47fff6e58e2baf35ae5b34d44695c617d44e0d54f6d7718f23ff44d391a5c618aa4f57956fd8

test:
  secret_key_base: 30c42eeaffbe34ddf09364ce513032b68876c6cb758c73b257712aa40ccc42e452c8e9a41b68236ada36ed5283507017111036069911e33b9b7b8d1fa987f761

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
